### ISSUE TITLE
Add a "Mine" button to mining page

### ISSUE THREAD

**Issue by Samyak2** [Samyak2/blockchat#1]
- Inside `miningpage.html` add a new button below the `tobemined` table 
 - Use bootstrap 4 to create the button
 - The button should say "Mine" or "Mine now"

**Comment by luismanfroni** [comment]
i can do it

**Comment by anton-dealmeida** [comment]
Would the button need to implement any form of onclick logic or have an event listener attached to it?

Also, would this be a primary or a secondary button?

**Comment by Samyak2** [comment]
> Would the button need to implement any form of onclick logic or have an event listener attached to it?

For now that is not required.

> Also, would this be a primary or a secondary button?

Primary
