### ISSUE TITLE
Add a reset password page

### ISSUE THREAD

**Issue by Samyak2** [Samyak2/blockchat#2]
- Make a `passwordreset.html` page
 - It should look like this
![image](https://user-images.githubusercontent.com/34161949/67653642-4e7d5200-f970-11e9-9df1-0bc4c681b4a9.png)
 - For the top navigation bar, copy the topbar list from `blockchainpage.html` and link the top bar css in the head using `<link rel="stylesheet" href="topbar.css">`
 - Use only HTML, CSS and Javascript
 - The button links can be kept empty for now
 - Make only the frontend, backend support will be added later

**Comment by enesacikoglu** [comment]
Hello,

Can I get it.

**Comment by Samyak2** [comment]
Yes, you can work on it.

**Comment by RajkumarMittal** [comment]
hey can i work on it? @Samyak2
