### ISSUE TITLE
Add a delete account page

### ISSUE THREAD

**Issue by Samyak2** [Samyak2/blockchat#3]
- Make a `deletepage.html` page
 - It should look like this
![image](https://user-images.githubusercontent.com/34161949/67653781-f266fd80-f970-11e9-9fde-200a7b4adc40.png)
 - For the top navigation bar, copy the topbar list from `blockchainpage.html` and link the top bar css in the head using `<link rel="stylesheet" href="topbar.css">`
 - Use only HTML, CSS and Javascript
 - The button links can be kept empty for now
 - Make only the frontend, backend support will be added later

**Comment by luismanfroni** [comment]
i can do it
